run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - gofumpt
    - revive
    - misspell
    - lll

linters-settings:
  lll:
    line-length: 140
    tab-width: 1
    # ignore comments and markdown-like lines for length
    exclude-pattern: "^\s*//|^\s*#|^\s*\*|^\s*```"
  revive:
    severity: warning

issues:
  exclude-use-default: false

