package testutil

import (
	"fmt"
	"os"
)

// GetAuthTokenPath returns the authentication token path for tests.
// This is the SINGLE source of truth for test authentication token location.
//
// The path MUST be provided via the ONEMOUNT_AUTH_PATH environment variable.
// There are NO fallback locations - this ensures tests fail fast with clear
// error messages if authentication is not properly configured.
//
// Setup Instructions:
//  1. Run: ./scripts/setup-auth-reference.sh
//  2. This configures Docker Compose to set ONEMOUNT_AUTH_PATH automatically
//  3. For manual runs: export ONEMOUNT_AUTH_PATH=/path/to/auth_tokens.json
//
// Docker Usage:
//
//	docker compose -f docker/compose/docker-compose.test.yml \
//	  -f docker/compose/docker-compose.auth.yml run --rm test-runner
//
// The auth override file (docker-compose.auth.yml) is generated by
// setup-auth-reference.sh and automatically sets ONEMOUNT_AUTH_PATH.
func GetAuthTokenPath() (string, error) {
	authPath := os.Getenv("ONEMOUNT_AUTH_PATH")

	if authPath == "" {
		return "", fmt.Errorf(`authentication token path not configured

ONEMOUNT_AUTH_PATH environment variable is not set.

To fix this:

1. Run the authentication reference setup script:
   ./scripts/setup-auth-reference.sh

2. This will:
   - Find your authentication tokens
   - Create docker/compose/docker-compose.auth.yml
   - Configure ONEMOUNT_AUTH_PATH automatically

3. Run tests with the auth override:
   docker compose -f docker/compose/docker-compose.test.yml \
     -f docker/compose/docker-compose.auth.yml run --rm test-runner

For manual testing outside Docker:
   export ONEMOUNT_AUTH_PATH=/path/to/your/auth_tokens.json

Expected token location (production):
   ~/.cache/onemount/{instance}/auth_tokens.json

Where {instance} is the escaped mount path (e.g., home-user-OneDrive)`)
	}

	// Verify the file exists
	if _, err := os.Stat(authPath); os.IsNotExist(err) {
		return "", fmt.Errorf(`authentication token file not found: %s

The ONEMOUNT_AUTH_PATH environment variable is set, but the file does not exist.

This usually means:
1. Tokens have not been created yet - run: ./build/onemount --auth-only
2. The path is incorrect - verify: ls -la %s
3. The reference system needs updating - run: ./scripts/setup-auth-reference.sh

Current ONEMOUNT_AUTH_PATH: %s`, authPath, authPath, authPath)
	}

	return authPath, nil
}

// MustGetAuthTokenPath returns the authentication token path or panics with a clear error.
// Use this in test setup when authentication is required.
func MustGetAuthTokenPath() string {
	path, err := GetAuthTokenPath()
	if err != nil {
		panic(err)
	}
	return path
}
