#!/bin/bash

# Script to set up authentication by reference (no copying, no symlinks)
# This finds the canonical token location and configures everything to reference it

set -e

echo "🔗 OneMount Authentication Reference Setup"
echo "=========================================="
echo ""

# Find the newest/best auth token file
echo "🔍 Finding canonical authentication token location..."

CANONICAL_TOKEN=""
CANONICAL_DATE=""

# Check common locations for fresh tokens
for token_path in \
    ~/.cache/onedriver/*/auth_tokens.json \
    ~/.cache/onemount/*/auth_tokens.json \
    ~/.config/onemount/auth_tokens.json \
    ~/auth_tokens.json; do
    
    if [[ -f "$token_path" ]]; then
        token_date=$(stat -c%Y "$token_path" 2>/dev/null || echo "0")
        token_size=$(stat -c%s "$token_path" 2>/dev/null || echo "0")
        
        # Skip empty files
        if [[ "$token_size" -lt 100 ]]; then
            continue
        fi
        
        echo "📄 Found: $token_path"
        echo "   Size: $token_size bytes"
        echo "   Date: $(date -d @$token_date 2>/dev/null || echo 'unknown')"
        
        # Keep track of the newest non-empty token
        if [[ "$token_date" -gt "${CANONICAL_DATE:-0}" ]]; then
            CANONICAL_TOKEN="$token_path"
            CANONICAL_DATE="$token_date"
        fi
        echo ""
    fi
done

if [[ -z "$CANONICAL_TOKEN" ]]; then
    echo "❌ No authentication tokens found!"
    echo ""
    echo "Please run authentication first:"
    echo "  ./scripts/manual-auth.sh"
    echo "  or"
    echo "  ./scripts/interactive-auth.sh"
    exit 1
fi

echo "✅ Canonical token location: $CANONICAL_TOKEN"
echo "   Date: $(date -d @$CANONICAL_DATE)"
echo ""

# Validate the token
if command -v jq >/dev/null 2>&1; then
    if ! jq empty "$CANONICAL_TOKEN" 2>/dev/null; then
        echo "❌ Token file is not valid JSON"
        exit 1
    fi
    
    # Check expiration
    expires_at=$(jq -r '.expires_at // 0' "$CANONICAL_TOKEN" 2>/dev/null || echo "0")
    current_time=$(date +%s)
    
    if [[ "$expires_at" != "0" ]]; then
        expires_date=$(date -d "@$expires_at" 2>/dev/null || echo "invalid")
        echo "⏰ Token expires: $expires_date"
        
        if [[ "$expires_at" -le "$current_time" ]]; then
            echo "❌ Token is already expired!"
            exit 1
        else
            echo "✅ Token is valid"
        fi
    else
        echo "⚠️  No expiration info in token"
    fi
else
    echo "⚠️  Cannot validate token (jq not available)"
fi

echo ""

# Create environment configuration
ENV_FILE=".env.auth"
echo "📝 Creating environment configuration: $ENV_FILE"

cat > "$ENV_FILE" << EOF
# OneMount Authentication Configuration
# Generated by setup-auth-reference.sh on $(date)

# Canonical authentication token location
# Note: Using ONEMOUNT_AUTH_PATH for consistency with test environment
ONEMOUNT_AUTH_PATH=$CANONICAL_TOKEN

# For Docker Compose - mount the parent directory
ONEMOUNT_AUTH_MOUNT_SOURCE=$(dirname "$CANONICAL_TOKEN")
ONEMOUNT_AUTH_MOUNT_TARGET=/tmp/auth-tokens
ONEMOUNT_AUTH_FILE_NAME=$(basename "$CANONICAL_TOKEN")

# Full path inside Docker container
ONEMOUNT_AUTH_PATH_DOCKER=/tmp/auth-tokens/$(basename "$CANONICAL_TOKEN")

# Export for shell scripts
export ONEMOUNT_AUTH_PATH="$CANONICAL_TOKEN"
export ONEMOUNT_AUTH_PATH_DOCKER="/tmp/auth-tokens/$(basename "$CANONICAL_TOKEN")"
EOF

echo "✅ Environment configuration created"
echo ""

# Update Docker Compose to use the environment file
echo "🐳 Updating Docker Compose configuration..."

# Create a docker-compose override file
OVERRIDE_FILE="docker/compose/docker-compose.auth.yml"
mkdir -p "$(dirname "$OVERRIDE_FILE")"

cat > "$OVERRIDE_FILE" << EOF
# Docker Compose override for authentication
# This file is generated by setup-auth-reference.sh
# It mounts the canonical auth token location into containers

name: onemount-test

services:
  test-runner:
    volumes:
      # Mount the canonical auth token directory (read-only)
      - $(dirname "$CANONICAL_TOKEN"):/tmp/auth-tokens:ro
    environment:
      # Point to the mounted token file
      - ONEMOUNT_AUTH_PATH=/tmp/auth-tokens/$(basename "$CANONICAL_TOKEN")

  unit-tests:
    volumes:
      - $(dirname "$CANONICAL_TOKEN"):/tmp/auth-tokens:ro
    environment:
      - ONEMOUNT_AUTH_PATH=/tmp/auth-tokens/$(basename "$CANONICAL_TOKEN")

  integration-tests:
    volumes:
      - $(dirname "$CANONICAL_TOKEN"):/tmp/auth-tokens:ro
    environment:
      - ONEMOUNT_AUTH_PATH=/tmp/auth-tokens/$(basename "$CANONICAL_TOKEN")

  system-tests:
    volumes:
      - $(dirname "$CANONICAL_TOKEN"):/tmp/auth-tokens:ro
    environment:
      - ONEMOUNT_AUTH_PATH=/tmp/auth-tokens/$(basename "$CANONICAL_TOKEN")

  coverage:
    volumes:
      - $(dirname "$CANONICAL_TOKEN"):/tmp/auth-tokens:ro
    environment:
      - ONEMOUNT_AUTH_PATH=/tmp/auth-tokens/$(basename "$CANONICAL_TOKEN")

  shell:
    volumes:
      - $(dirname "$CANONICAL_TOKEN"):/tmp/auth-tokens:ro
    environment:
      - ONEMOUNT_AUTH_PATH=/tmp/auth-tokens/$(basename "$CANONICAL_TOKEN")
EOF

echo "✅ Docker Compose override created: $OVERRIDE_FILE"
echo ""

# Test the configuration
echo "🧪 Testing authentication reference..."

# Source the environment file
source "$ENV_FILE"

echo "   Canonical path: $ONEMOUNT_AUTH_PATH"
echo "   Docker path: $ONEMOUNT_AUTH_PATH_DOCKER"
echo "   File exists: $(test -f "$ONEMOUNT_AUTH_PATH" && echo "✅ YES" || echo "❌ NO")"

echo ""
echo "🎉 Authentication reference setup complete!"
echo ""
echo "📋 Usage:"
echo "   # Run tests with auth reference:"
echo "   docker compose -f docker/compose/docker-compose.test.yml -f $OVERRIDE_FILE run --rm test-runner"
echo ""
echo "   # Or use the wrapper script:"
echo "   COMPOSE_FILE=\"docker/compose/docker-compose.test.yml:$OVERRIDE_FILE\" ./scripts/timeout-test-wrapper.sh \"TestPattern\" 60"
echo ""
echo "💡 The tokens are now referenced directly - no copying or symlinking!"
echo "   When tokens are refreshed, just run this script again to update the reference."