# Docker Compose configuration for Elastic GitHub Actions Runners
# Provides auto-scaling capabilities for OneMount CI/CD

version: '3.8'

services:
  # Elastic Runner Manager - monitors and scales runners
  elastic-manager:
    build:
      context: ../..
      dockerfile: packaging/docker/Dockerfile.github-runner
    image: onemount-github-runner:latest
    container_name: onemount-elastic-manager
    
    # Mount Docker socket for container management
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../..:/workspace:ro
      - elastic-manager-data:/opt/actions-runner/_work
    
    # Network configuration
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 8.8.4.4
    
    # Restart policy
    restart: unless-stopped
    
    # Run the elastic manager
    working_dir: /workspace
    command: ["exec", "/usr/local/bin/elastic-runner-manager.sh", "monitor"]

    # Override environment variables to ensure they're available
    environment:
      - DOCKER_HOST=${DOCKER_HOST:-tcp://172.16.1.104:2376}
      - MIN_RUNNERS=${MIN_RUNNERS:-1}
      - MAX_RUNNERS=${MAX_RUNNERS:-5}
      - SCALE_UP_THRESHOLD=${SCALE_UP_THRESHOLD:-2}
      - SCALE_DOWN_THRESHOLD=${SCALE_DOWN_THRESHOLD:-0}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-30}
      - COOLDOWN_PERIOD=${COOLDOWN_PERIOD:-300}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - AUTH_TOKENS_B64=${AUTH_TOKENS_B64:-}
    
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "-f", "elastic-runner-manager"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Base runner template (not started by default)
  runner-template:
    build:
      context: ../..
      dockerfile: packaging/docker/Dockerfile.github-runner
    image: onemount-github-runner:latest
    
    # Environment configuration
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - RUNNER_NAME=${RUNNER_NAME:-onemount-runner-elastic}
      - RUNNER_LABELS=self-hosted,Linux,onemount-testing,optimized,elastic
      - RUNNER_GROUP=${RUNNER_GROUP:-Default}
      - AUTH_TOKENS_B64=${AUTH_TOKENS_B64:-}
    
    # Mount configuration
    volumes:
      - ../..:/workspace:rw
      - runner-template-work:/opt/actions-runner/_work
    
    # Enable FUSE support for filesystem testing
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    
    # Network configuration
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 8.8.4.4
    
    # Don't start automatically
    profiles:
      - template
    
    # Default command
    command: ["run"]

  # Monitoring dashboard (optional)
  dashboard:
    image: nginx:alpine
    container_name: onemount-elastic-dashboard
    
    # Simple status dashboard
    volumes:
      - ./elastic-dashboard.html:/usr/share/nginx/html/index.html:ro
    
    # Expose on port 8080
    ports:
      - "8080:80"
    
    # Restart policy
    restart: unless-stopped
    
    # Don't start by default
    profiles:
      - dashboard

volumes:
  # Persistent storage for elastic manager
  elastic-manager-data:
    driver: local
  
  # Template runner work directory
  runner-template-work:
    driver: local

networks:
  default:
    driver: bridge
